Updated tangential matrix computation
andreas-apostolatos/cane pull request #12
Opened 2020-05-13 11:31 UTC by MarkoLeskovar

Dear Andreas,

I finished with the selected tasks that you gave me. I this branch I did the following:

1. Fixed the GiD input files so that they work with the latest parser and non-linear analysis
2. Relaxed the tolerances in unit tests so that they also pass on Windows machine
3. Implement page-wise computation of tangential stiffness matrix for CST
4. Compared results of new function with the old tanMtx computation and they give the same results

I noticed however, that the solver related to the transient plate in membrane action analysis is missing from the GiD repository, even though "main" script and also an unit test for it exist. Is this intentional or did you somehow deleted it by mistake? 

Please write me an email if you have any questions or remarks.

Best regards,
Marko Leskovar

2020-05-14 11:12 UTC, andreas-apostolatos requested changes
Hi Marko,

thanks a lot for the excellent work! Can you please revert all changes you did in the unit tests? I know that some of them fail under windows due to very strict tolerances but I would like to take care of them myself as it is a very decisive part of the code.

Kind Regards,
Andreas

2020-05-14 11:12 UTC, andreas-apostolatos commented on unitTest/@testFEMComputationalFluidDynamicsAnalysis/testFEM4NavierStokesTransientALE2D.m
> +absTol = 1e-14; % tolerance w.r.t our value
Please revert the changes in the unit tests, I would like to fix them myself under Windows.

2020-05-14 11:12 UTC, andreas-apostolatos commented on unitTest/@testFEMComputationalFluidStructureInteractionAnalysis/testFluidStructureInteractionSpringMass.m
> +absTol = 1e-8;
Please revert the changes in the unit tests, I would like to fix them myself under Windows.

2020-05-14 11:12 UTC, andreas-apostolatos commented on unitTest/@testFEMContactMechanicsAnalysis/testFrictionlessSignoriniContactHertz2D.m
> +absTol5 = absTol*1e6;
Please revert the changes in the unit tests, I would like to fix them myself under Windows.

2020-05-14 11:12 UTC, andreas-apostolatos commented on unitTest/@testFEMContactMechanicsAnalysis/testFrictionlessSignoriniContactWedge2D.m
> +absTol2 = absTol*1e3;
Please revert the changes in the unit tests, I would like to fix them myself under Windows.

2020-05-14 11:12 UTC, andreas-apostolatos commented on unitTest/@testFEMThermalConductionAnalysis/testTransientSquareCavity.m
> +absTol2 = 1e-12*1e2;
Please revert the changes in the unit tests, I would like to fix them myself under Windows.

2020-05-14 11:12 UTC, andreas-apostolatos commented on unitTest/@testFEMThermalConductionAnalysis/testTransientWallHeating.m
> +absTol3 = 1e-12*1e3;
Please revert the changes in the unit tests, I would like to fix them myself under Windows.

2020-05-14 11:12 UTC, andreas-apostolatos commented on unitTest/@testIGAMembraneAnalysis/testNonlinearMembraneAnalysis.m
> +absTol = 1e-12;
Please revert the changes in the unit tests, I would like to fix them myself under Windows.

2020-05-14 11:12 UTC, andreas-apostolatos commented on unitTest/@testIGAMembraneAnalysis/testTransientNonlinearMembraneAnalysis.m
> +absTol = 1e-12;
Please revert the changes in the unit tests, I would like to fix them myself under Windows.

2020-05-16 12:06 UTC, MarkoLeskovar commented
Dear Andreas,

This branch should be now finished and ready to merge.

2020-05-16 20:18 UTC, andreas-apostolatos approved these changes

2020-05-16 20:19 UTC, merged